		<link href="<%=contextPath%>/js/bootstrap/css/bootstrap.css"
			rel="stylesheet" />
		<link
			href="<%=contextPath%>/js/bootstrap/css/bootstrap-responsive.css"
			rel="stylesheet" />
		<link href="<%=contextPath%>/js/bootstrap/css/docs.css"
			rel="stylesheet" />
		<link href="<%=contextPath%>/js/bootstrap/css/prettify.css"
			rel="stylesheet" />			
		<style type="text/css">
body {
	padding-top: 60px;
	padding-bottom: 40px;
}
</style>