		<link href="<%=contextPath%>/js/bootstrap/css/bootstrap.css"
			rel="stylesheet" />
		<link href="<%=contextPath%>/js/bootstrap/css/bootstrap-responsive.css"
			rel="stylesheet" />
		<link href="<%=contextPath%>/js/bootstrap/css/docs.css"
			rel="stylesheet" />
		<link href="<%=contextPath%>/js/bootstrap/css/prettify.css"
			rel="stylesheet" />			
		<style type="text/css">
body {
	background-color:#DDE1E5;
}
</style>
		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
		<link href="<%=contextPath%>/img/favicon.png" rel="shortcut icon" />