<%@ page trimDirectiveWhitespaces="true" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>	
<%
	String contextPath = (String)request.getContextPath();
	
	/*
	response.setHeader("Expires","Mon, 26 Jul 1997 05:00:00 GMT");
	response.setHeader("Last-Modified","Mon, 26 Jul 1997 05:00:00 GMT");
	response.setHeader("Cache-Control","no-store, no-cache, must-revalidate, max-age=0");
	response.setHeader("Cache-Control","post-check=0, pre-check=0");
	response.setHeader("Pragma","no-cache");
	*/
%>
